/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chat.GUI;

import java.awt.Color;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.Timer;

/**
 *
 * @author Visual-Studio
 */
public class frmLoad extends javax.swing.JFrame {

    private Timer time_;
    private int nCheck_;
    public frmLoad(client Cl) {
        initComponents();
        initComponents2();
        startLoad(Cl);
    }

    private void initComponents2() {
        setLocationRelativeTo(this);
        getContentPane().setBackground(new Color(255,255,255));
        nCheck_ = 0;
    }
    
    private void startLoad(client Cl) {
        time_ = new Timer(1000, (ActionEvent e) -> {
               nCheck_++;
               if(nCheck_ == 2){
                   Cl.setVisible(true);
                   time_.stop();
                   dispose();
               }
        });
        time_.start();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbImageLoad = new javax.swing.JLabel();
        lbPanel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(347, 475));
        setMinimumSize(new java.awt.Dimension(347, 475));
        setPreferredSize(new java.awt.Dimension(347, 475));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbImageLoad.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbImageLoad.setForeground(new java.awt.Color(30, 144, 255));
        lbImageLoad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_chat_server/image/login/loading.gif"))); // NOI18N
        lbImageLoad.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lbImageLoad, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 170, 90));

        lbPanel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbPanel.setForeground(new java.awt.Color(30, 144, 255));
        lbPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_chat_server/image/iconsLoad/Facebook Messenger_100px.png"))); // NOI18N
        getContentPane().add(lbPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 130, 140));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(frmLoad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(frmLoad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(frmLoad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(frmLoad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> {
//            new frmLoad().setVisible(true);
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbImageLoad;
    private javax.swing.JLabel lbPanel;
    // End of variables declaration//GEN-END:variables
}
